name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

env:
  CI: true
  DEBIAN: noninteractive

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install LuaCheck
        run: luarocks install luacheck

      - name: Run linter
        run: find lib/ -iname '*.lua' | xargs luacheck --formatter TAP

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit']
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install dependencies
        shell: /bin/bash -o errexit -o pipefail -o xtrace {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gobject-introspection libgirepository1.0-dev
          luarocks install busted
          luarocks install lgi
          luarocks install --server=https://luarocks.org/dev async.lua

      - name: Run tests
        run: busted --config-file=.busted.lua --helper=tests/_helper.lua --output=TAP tests
